name=containerd
description=Containerd OCI Runtime Daemon
exec=/usr/bin/containerd
args=--config /etc/containerd/config.toml
pidfile=/run/containerd/containerd.pid
logfile=/var/log/containerd.log
autostart=true
