# Node.js app (npm start / next start). Generated by ziroctld; base images pinned by digest.
FROM docker.io/library/node:24-alpine@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1 AS build
WORKDIR /app
COPY . .
RUN {{.Setup}}{{.Install}}
{{- if .Build}}
RUN {{.Build}}
{{- end}}

FROM docker.io/library/node:24-alpine@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1
WORKDIR /app
ENV NODE_ENV=production PORT={{.Port}} HOSTNAME=0.0.0.0
{{- if .Setup}}
RUN {{.Setup}}true
{{- end}}
COPY --from=build --chown=node:node /app /app
USER node
EXPOSE {{.Port}}
CMD {{.Start}}
